# Generated by Django 4.2.11 on 2024-05-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'labels',
                'db_table_comment': 'Stores information about event labels for a user.',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_start', models.DateTimeField()),
                ('date_stop', models.DateTimeField()),
            ],
            options={
                'db_table': 'notifications',
                'db_table_comment': 'Stores information about the notifications.',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('birthday', models.DateField()),
                ('avatar', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'db_table_comment': 'Stores information about registered users of the application.',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelTableComment(
            name='event',
            table_comment='Stores information about registered events of a user application.',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='calendar_app.user')),
                ('language', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=50)),
                ('time_format', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('event_reminder', models.BooleanField()),
                ('activity_notifications', models.BooleanField()),
                ('week_start_day', models.CharField(max_length=50)),
                ('weekend_visibility', models.BooleanField()),
            ],
            options={
                'db_table': 'user_settings',
                'db_table_comment': 'Stores information about the users personal settings.',
            },
        ),
        migrations.CreateModel(
            name='CalendarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.user')),
            ],
            options={
                'verbose_name_plural': 'Calendar Users',
                'db_table': 'calendar_users',
                'db_table_comment': 'Stores information about users assigned to calendars.',
                'unique_together': {('user', 'agenda')},
            },
        ),
    ]
