# Generated by Django 5.0.4 on 2024-05-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_alter_event_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
