# Generated by Django 5.0.4 on 2024-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_alter_event_recurrence_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaruser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=50),
            preserve_default=False,
        ),
    ]
