# Generated by Django 5.0.4 on 2024-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_calendaruser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
