# Generated by Django 5.0.4 on 2024-06-06 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_timeblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shared_calendars', through='calendar_app.CalendarUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CalendarPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_event_details', models.BooleanField(default=False)),
                ('can_create_events', models.BooleanField(default=False)),
                ('can_edit_events', models.BooleanField(default=False)),
                ('can_delete_events', models.BooleanField(default=False)),
                ('can_invite_others', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_permissions',
                'db_table_comment': 'Stores permissions of users for a calendar.',
                'unique_together': {('user', 'calendar')},
            },
        ),
    ]
