# Generated by Django 5.0.4 on 2024-06-11 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0011_calendar_users_calendarpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendar'),
        ),
    ]
