# Generated by Django 5.0.4 on 2024-06-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0013_alter_notification_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendar'),
        ),
    ]
